codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "30...80"

  status:
    project: yes
    patch: yes
    changes: yes
    threshold: 100% # Allow the coverage to drop by X% and posting a success status.
    target: 0% # Choose minimum coverage ratio the commit must meet to be considered a success status.

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
