version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
before_build:
- cmd: >-
    git submodule init

    git submodule update --init --recursive

    nuget restore Testable.sln
build:
  project: Testable.sln
  verbosity: minimal

# Set OpenCover setting according to below URL
# https://github.com/OpenCover/opencover/wiki/Usage

test_script:
- ps: >-
    $test_dll_dir = (Resolve-Path "*.Tests\bin\$env:CONFIGURATION").ToString()

    $opencover = (Resolve-Path ".\packages\OpenCover.*\tools\OpenCover.Console.exe").ToString()

    $targetargs = """$((Resolve-Path "$test_dll_dir\*.Tests.dll").ToString())"" -noshadow"

    $filter = "+[Testable*]* -[*.Tests*]*"

    $runner = (Resolve-Path "src\packages\xunit.runner.console.*\tools\xunit.console.x86.exe").ToString()

    regsvr32 x86\OpenCover.Profiler.dll

    regsvr32 x64\OpenCover.Profiler.dll

    echo "runner"

    echo $runner

    & $opencover -register:user -target:$runner -targetargs:$targetargs -filter:$filter -log:All -returntargetcode -hideskipped:All -targetdir:$test_dll_dir -output:opencoverCoverage.xml

    $env:Path = "C:\Python34;C:\Python34\Scripts;$env:Path"

    python -m pip install --upgrade pip

    pip install codecov

    &{codecov -f "opencoverCoverage.xml"}

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
